# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  version="=v2.0.8"
  name = "github.com/pingcap/tidb"

[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "3bcb09397d6d88e7676a9bc8433ca11ba5304837"

[[override]]
  name = "github.com/coreos/etcd"
  version = "=3.2.14"

[[override]]
  name = "golang.org/x/sys"
  revision = "master"

[[override]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "=1.7.5"

[[override]]
  name = "github.com/pingcap/kvproto"
  revision = "2cf2492c337c4d0281d8ead8686d47764f1df6c4"

[[override]]
  name = "github.com/pingcap/tipb"
  revision = "2d5073e5521a10f8db2adc0eaab2c46ca0a151d9"
